# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shikari < Formula
  desc "An opinionated Dev Cluster Provisioner using Lima"
  homepage "https://github.com/ranjandas/shikari"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/Ranjandas/shikari/releases/download/v0.3.0/shikari_Darwin_x86_64.tar.gz"
      sha256 "55d04f3e3a14295665d1901a79065b755c479163dc0683eb91308e1ec8542209"

      def install
        bin.install "shikari"
      end
    end
    on_arm do
      url "https://github.com/Ranjandas/shikari/releases/download/v0.3.0/shikari_Darwin_arm64.tar.gz"
      sha256 "244ffbe9fdea79edb0cccdaf51bd17d040523c6e2b7580e998ef2b9aba9fa144"

      def install
        bin.install "shikari"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ranjandas/shikari/releases/download/v0.3.0/shikari_Linux_x86_64.tar.gz"
        sha256 "b6ba74edb6daaf58c0bf8bac73adbba44c326eba854ae5c59488a81c45c4efd8"

        def install
          bin.install "shikari"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ranjandas/shikari/releases/download/v0.3.0/shikari_Linux_arm64.tar.gz"
        sha256 "0081e1809d53d567f02aa534fa213d7d93a00b2d02fb32728cdf0046901aadb4"

        def install
          bin.install "shikari"
        end
      end
    end
  end
end
