# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shikari < Formula
  desc "An opinionated Dev Cluster Provisioner using Lima"
  homepage "https://github.com/ranjandas/shikari"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/Ranjandas/shikari/releases/download/v0.4.0/shikari_Darwin_x86_64.tar.gz"
      sha256 "793641c066bfc647bbd67b09604258ccb89b585af14f3305cf4eac0e08a3d0dd"

      def install
        bin.install "shikari"
      end
    end
    on_arm do
      url "https://github.com/Ranjandas/shikari/releases/download/v0.4.0/shikari_Darwin_arm64.tar.gz"
      sha256 "a0ed70ccb17cc7b25e39876e92a27792322f3ac2305489656b6fe25229fbca3b"

      def install
        bin.install "shikari"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ranjandas/shikari/releases/download/v0.4.0/shikari_Linux_x86_64.tar.gz"
        sha256 "899a81a7fd6bb03715d26437ac1fa6219451ca0eef10504084c14098c26f6191"

        def install
          bin.install "shikari"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ranjandas/shikari/releases/download/v0.4.0/shikari_Linux_arm64.tar.gz"
        sha256 "cb01d1f216b1828923d8ed1d74edb54b9e8a996687eed6b45d82ef8d1595b812"

        def install
          bin.install "shikari"
        end
      end
    end
  end
end
